output_global_parent_dir: results
output_dir: tb_qwen_gsm8k
dataset_name: openai/gsm8k
bf16: True
#fp16: True
total_episodes: 140000 
response_length: 512 
num_ppo_epochs: 1
num_mini_batches: 1
learning_rate: 1e-5
per_device_train_batch_size: 10 #20
per_device_eval_batch_size: 32 #128
gradient_accumulation_steps: 7
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
sft_model_path: Qwen/Qwen2.5-1.5B-Instruct
local_rollout_forward_batch_size: 36 #72
non_eos_penalty: False
stop_token: eos
save_strategy: steps
save_steps: 0.25
hub_strategy: all_checkpoints
logging_steps: 100
num_sample_generations: 20